steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/inventori-frontend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/inventori-frontend:$SHORT_SHA'
      - '.'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/inventori-frontend'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--filename=.'
      - '--image=gcr.io/$PROJECT_ID/inventori-frontend:$SHORT_SHA'
      - '--location=asia-southeast1'
      - '--output=/workspace/deploy/'

images:
  - 'gcr.io/$PROJECT_ID/inventori-frontend:latest'
  - 'gcr.io/$PROJECT_ID/inventori-frontend:$SHORT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
